config/routes.rb
Rails.application.routes.draw do
 

  get 'staticpages/about'

  get 'staticpages/do'
  get 'blocks/block_archive'
  devise_for :users
  resources :clients
  resources :blocks
  resources :jobs

   root 'clients#index'

end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
  after_create :live_act
  validates_presence_of :job_id
  validates_presence_of :time

  def live_act
  	update_attribute(:live, true)
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :user
	has_many :jobs, dependent: :destroy
	has_many :blocks, through: :jobs, dependent: :destroy
	accepts_nested_attributes_for :jobs, reject_if: proc {|attributes| attributes['story'].blank?}
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :blocks, dependent: :destroy
  validates_presence_of :client_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :clients, dependent: :destroy
         has_many :jobs, dependent: :destroy
         has_many :blocks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected
  def user_not_authorized
  	redirect_to edit_user_registration_path, alert: "No can do old chum!"
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
  	@blocks = Block.where(user_id: current_user.id, live: true)
  end

  def new
  	
  	#@block = Block.new
  	@block = current_user.blocks.build
  	@client = Client.find(params[:client])
  	@job = Job.where(client_id: @client.id, user_id: current_user.id)
  	
  end

  def create
  	@block = current_user.blocks.build(block_params)
  	if @block.save
  		redirect_to @block
  	else
  		render 'new'
  	end
  end

  def show
  	@block = Block.find_by(id: params[:id])
    authorize @block
  end

  def edit
    @block = Block.find(params[:id])
    @job = Job.where(client_id: @block.job.client.id)
    authorize @block
  end

  def update
    @block = Block.find(params[:id])
    if @block.update(block_params)
      redirect_to @block
    else
      render 'edit'
    end
  end

  def destroy
    @block = Block.find(params[:id])
    @block.destroy
      redirect_to blocks_path
  end

  def block_archive
    @blocks = Block.where(user_id: current_user.id, live: false)
  end

  private 

  	def block_params
  		params.require(:block).permit(:des, :time, :user_id, :job_id, :live )
  	end

  	def correct_user
    	@block = current_user.block.find_by(id: params[:id])
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :correct_user

  def index
  	@clients = Client.where(user_id: current_user.id)
  end

  def edit
    @client = Client.find(params[:id])
    authorize @client
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client
    else
      render 'new'
    end
  end

  def new
  	@client = current_user.clients.build
  end

  def create
  	@client = current_user.clients.build(client_params)
	if @client.save
		redirect_to @client
	else
		render 'new'
	end
  end

  def show
  	@client = Client.find(params[:id])
    authorize @client
    
  end

  def destroy
    authorize @client
    @client.destroy
    redirect_to root_path
  end

  private

  	def client_params
  		params.require(:client).permit(:name, :about, :rate, jobs_attributes: [:name, :info, :id])
  	end

  	def client_set
  		@client = Client.find(params[:id])
  	end

    def correct_user
      @client = current_user.clients.find_by(id: params[:id])
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.where(user_id: current_user.id)
    
    @tot = 0



    @more = 0
    @jobs.each do |p|
    @total = p.blocks
    @total.each do |b|
      if b.time?
        @more += b.time
      end

    end
  end 
  end

  def show
    @job = Job.find(params[:id])
    authorize @job
    @total = @job.blocks
    @more = 0
    @total.each do |b|
      if b.time?
        @more += b.time 
      end
    end
  end

  def edit
    @job = Job.find(params[:id])
    authorize @job
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def new
  	@job = current_user.jobs.build
  end

  def create
  	@job = current_user.jobs.build(job_params)
	if @job.save
		redirect_to @job
	else
		render 'new'
	end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  private 

  	def job_params
  		params.require(:job).permit(:name, :info, :client_id)
  	end

  	def correct_user
    	@job = current_user.job.find_by(id: params[:id])
    end

    def client_set
  		@job = Job.find(params[:id])
  	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def about
  end

  def do
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
	
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/blocks/_blockform.html.erb
<div class="container">

	<div class="col-md-4 col-md-offset-4">
		<h1>Client: <%= @client.name%></h1>
		<div class="clock"></div>
	</div>
</div>


<br> 
<script>
	var clock = $('.your-clock').FlipClock({
		autoStart:false
});

	$(document).ready(function(){
		$('.start').click(function(){
			$('.clock').timer({format: '%H:%M:%S'}, {seconds: 0});
		})
		$('.stop').click(function(){
			$('.clock').timer('pause');
		})
		$('.reset').click(function(){
			$('.clock').timer('reset');
		})
		$('.get_time').click(function(){
		var moment = $('.clock').data('seconds');

		$('.secs').val(+ moment)
		console.log(moment);


	})

		

	})


</script>


<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-primary start">Start</button>
  <button type="button" class="btn btn-success get_time">Get time</button>
  <button type="button" class="btn btn-info stop">Stop</button>
  
  
</div>

<%= link_to 'Create job', new_job_path, class: 'btn btn-primary' %>

<%= simple_form_for @block do |f|%>

<% if @block.errors.any? %>

	<div id="errors">
		<%= @block.errors.count %> prevented this from saving.
	</div>

	<ul>
		<% @block.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>

<% end %>

<div class="panel-body">
	<%= f.input :job_id, collection: @job, input_html: {class: 'form-control'}, prompt: "Choose a job" %>
	<%= f.input :des, input_html: {class: 'form-control'} %>
	<%= f.input :time, input_html: {class: 'form-control secs'} %>
</div>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/blocks/block_archive.html.erb
<table class="table table-striped">
	<tr>
		<th>Client</th>
		<th>Job</th>
		<th>Block</th>
		<th>Time</th>
	</tr>
	<% @blocks.each do |a| %>
	<tr>
		<td><%= link_to a.job.client.name, client_path(a.job.client.id) %></td>
		<td><%= link_to a.job.name, job_path(a.job.id) %></td>
		<td><%= link_to a.des, block_path(a) %></td>
		<td><%= a.time / 60 %></td>
	</tr>
	<% end %>
</table>

app/views/blocks/edit.html.erb
<h1>Blocks#edit</h1>


<p>Find me in app/views/blocks/edit.html.erb</p>

<p>This will require a different clock. Or the same clock but an option that grabs the time from time seconds form. </p>

<p>Alternatively, could just use a different clock here but one that grabs the number from the form.</p>


<%= simple_form_for @block do |f|%>

<% if @block.errors.any? %>

	<div id="errors">
		<%= @block.errors.count %> prevented this from saving.
	</div>

	<ul>
		<% @block.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>

<% end %>

<div class="panel-body">
	<%= f.input :job_id, collection: @job, input_html: {class: 'form-control'}, prompt: "Choose a job" %>
	<%= f.input :des, input_html: {class: 'form-control'} %>
	<%= f.input :time, input_html: {class: 'form-control seconds'} %>
	<%= f.input :live, as: :boolean, checked_value: 1, unchecked_value: 0 %>

</div>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/blocks/index.html.erb
<table class="table table-striped">
	<tr>
		<th>Client</th>
		<th>Job</th>
		<th>Block</th>
		<th>Update</th>
		<th>Time</th>
		<th>Delete</th>
	</tr>
	<% @blocks.each do |a| %>
	<tr>
		<td><%= link_to a.job.client.name, client_path(a.job.client.id) %></td>
		<td><%= link_to a.job.name, job_path(a.job.id) %></td>
		<td><%= link_to a.des, block_path(a) %></td>
		<td><%= a.updated_at %></td>
		<td><%= a.time / 60 %></td>
		<td><%= link_to 'delete', block_path(a), method: :delete, class: "btn btn-danger" %></td>	
	</tr>
	<% end %>
</table>

<%= link_to 'archive', blocks_block_archive_path %>

app/views/blocks/new.html.erb
<%= render 'blockform' %>

app/views/blocks/show.html.erb
<h1 style="text-align: center;">Block show</h1>







<ul class="list-group">
	<li class="list-group-item">Client: <%= link_to @block.job.client.name, client_path(@block.job.client.id) %></li>
	<li class="list-group-item">Job: <%= link_to @block.job.name, job_path(@block.job.id) %></li>
	<li class="list-group-item">Block created: <%= @block.created_at %></li>
	<li class="list-group-item">Block last updated: <%= @block.updated_at %></li>
	<li class="list-group-item">Block description: <%= @block.des %></li>
	<li class="list-group-item">Block time: <%= @block.time / 60 %> minutes or <%= @block.time %> seconds </li>
	<li class="list-group-item">Live Job: <%= @block.live %></li>
</ul>



<%= link_to 'Edit', edit_block_path(@block), class: "btn btn-success" %>
<%= link_to 'Delete', block_path(@block), method: :delete, class: "btn btn-danger" %>

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f|%>

<% if @client.errors.any? %>

	<div id="errors">
		<%= @client.errors.count %> prevented this from saving.
	</div>

	<ul>
		<% @client.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>

<% end %>

<div class="panel-body">
	<%= f.input :name, input_html: {class: 'form-control'} %>
	<%= f.input :about, input_html: {class: 'form-control'} %>
	<%= f.input :rate, input_html: {class: 'form-control'} %>
</div>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/clients/index.html.erb
<h1>Clients</h1>
<br>


<table class="table">
  <th>Client</th>
  <th>Create job</th>
  <th>Create block</th>
  <th>Delete client</th>
  <% @clients.each do |client| %>
	<tr>
		<td><%= link_to client.name, client_path(client) %></td>
		<td><%= link_to 'Job', new_job_path, class: "btn btn-primary" %></td>
		<td><%= link_to 'Block', new_block_path(client: client.id), class: "btn btn-info" %></td>
		<td><%= link_to 'delete', client_path(client), method: :delete, class: "btn btn-danger" %></td>
	</tr>
	<% end %>
</table>
<br>
<%= link_to 'Add Client', new_client_path, class: "btn btn-success" %>

app/views/clients/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<h1>New Client</h1>

	<%= render 'form.html.erb' %>
	
	

</div>

app/views/clients/show.html.erb
<div class="col-md-8 col-md-offset-2">	

<h1><%= @client.name %></h1>

<p><%= @client.about %></p>

<p>The hourly rate is: <%= @client.rate %></p>

<h3>List of jobs</h3>
<ul class="list-group">
<% @client.jobs.each do |a| %>
	<li class="list-group-item"><%= link_to a.name, job_path(a) %> <br><%= a.info %> Total blocks: <%= a.blocks.count %> Live blocks: <%= a.blocks.where(live: true).count %></li>
	<% a.blocks.each do |c| %>
	<% if c.live == true %>
	<li class="list-group-item"> <%= link_to c.des, block_path(c) %> Time: <%= c.time / 60 %> minutes</li>
	<% end %>
	<% end %>
<% end %>
</ul>



<%= link_to 'Delete', client_path, method: :delete, class: "btn btn-danger" %>
<%= link_to 'Edit', edit_client_path, class: "btn btn-primary" %>
<%= link_to 'New Job', new_job_path, class: "btn btn-primary" %>
<%= link_to 'New Block', new_block_path(client: @client.id), class: "btn btn-success" %>

<br>
<br>


</div> 

app/views/jobs/_jobform.html.erb
<%= simple_form_for @job do |f|%>

<% if @job.errors.any? %>

	<div id="errors">
		<%= @job.errors.count %> prevented this from saving.
	</div>

	<ul>
		<% @job.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>

<% end %>

<div class="panel-body">
	<%= f.input :client_id, collection: Client.where(user_id: current_user.id), input_html: {class: 'form-control'} %>
	<%= f.input :name, input_html: {class: 'form-control'} %>
	<%= f.input :info, input_html: {class: 'form-control'} %>
</div>
<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit</h1>

<h1><%= link_to @job.client.name, client_path(@job.client.id) %></h1>

<%= render 'jobform' %>

app/views/jobs/index.html.erb
<h1>Jobs Index</h1>
<br>
<table class="table table-striped">
	<th>Client</th>
	<th>Name</th>
	
	<th>Total time</th>
	<% @jobs.each do |a| %>
	<tr>
		<td><%= link_to a.client.name, client_path(a.client_id) %></td>
		<td><%= link_to a.name, job_path(a) %></td>
		<% a.blocks.each do |l| %>
		<% if l.live == true %>
		<% @tot += l.time / 60%>
		<% end %>
		
		<% end %>
		<td><%= @tot %></td>
		
	
	</tr>
	<% end %>
</table>

app/views/jobs/new.html.erb
<h1>Job</h1>

<%= render 'jobform' %>

app/views/jobs/show.html.erb
<h1><%= @job.name %> job page for '<%= @job.info %>'</h1>
<h3>For: <%= link_to @job.client.name, client_path(@job.client.id) %></h3>


<br>

<table class="table">
	<tr>
	<th>Block</th>
	<th>Date</th>
	<th>Time</th>
	</tr>
	<% @job.blocks.each do |a| %>
	<tr>
		
		<td><%= link_to a.des, block_path(a) %></td>
		<td><%= a.updated_at %></td>
		<td><%= a.time / 60 %></td>
		
	</tr>
	<% end %>
</table>

<p>Total time:<%= @more / 60 %> minutes</p>

<%= link_to 'Edit', edit_job_path, class: "btn btn-primary" %>
<%= link_to 'New block', new_block_path(client: @job.client_id), class: "btn btn-success" %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Timesheets", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Blocks', blocks_path %></li>
        <li><%= link_to 'Jobs', jobs_path %></li>
        <li><%= link_to 'New client', new_client_path %></li>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>


        
        
        
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sheet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/nav' %>
<div class="container">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</div>
</body>
</html>

app/views/staticpages/about.html.erb
<div class="jumbotron">
	<h2>About</h2>
</div>

<p>This site is about time management. More specifically it aims to do two things: allow you to work out how much time you're spending on projects. And two, work out how much money that work is making for you and whether it is worth your while.</p>

<p>The principle motivation is the idea that time needs to be blocked </p>

app/views/staticpages/do.html.erb
<div class="jumbotron">
	<h2>Things to do</h2>
</div>

<div class="col-md-6 col-md-offset-3">
	<ol>
		<li>Add in live or dead to blocks as booleans.</li>
		<li>List interuptions.</li>
		<li>Lay out by date. Put in a checkbox making it the last calendar month or forever.</li>
		<li>Add in your principle worth and workout how much you are earning per hour based on that.</li>
	</ol>
</div>